# Generated by Django 3.0.8 on 2021-10-25 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2021, 10, 25, 5, 10, 41, 158736))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger')),
            ],
        ),
    ]
