# Generated by Django 3.0.8 on 2021-10-25 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 6, 44, 20, 69710)),
        ),
    ]
