# Generated by Django 3.0.8 on 2021-10-25 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_auto_20211025_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='passenger_id',
            new_name='passenger',
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 6, 48, 37, 708020)),
        ),
    ]
