# Generated by Django 3.0.8 on 2021-10-25 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0006_auto_20211025_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 7, 25, 55, 837355, tzinfo=utc)),
        ),
    ]
