# Generated by Django 3.0.8 on 2021-10-25 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0012_auto_20211025_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 15, 41, 52, 582374, tzinfo=utc)),
        ),
    ]
