# Generated by Django 3.0.8 on 2021-10-26 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0023_auto_20211026_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 7, 41, 41, 962665, tzinfo=utc)),
        ),
    ]
