# Generated by Django 3.0.8 on 2021-10-27 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0028_auto_20211027_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 4, 53, 40, 78300, tzinfo=utc)),
        ),
    ]
