# Generated by Django 3.0.8 on 2021-10-27 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0031_auto_20211027_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 8, 20, 43, 294338, tzinfo=utc)),
        ),
    ]
