# Generated by Django 3.0.8 on 2021-10-28 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0032_auto_20211028_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 16, 55, 36, 307641, tzinfo=utc)),
        ),
    ]
