# Generated by Django 3.0.8 on 2021-11-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0033_auto_20211028_1555'),
        ('passenger', '0033_auto_20211029_1730'),
    ]

    operations = [
    ]
