# Generated by Django 3.0.8 on 2021-10-27 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0034_auto_20211027_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 10, 21, 57, 105966, tzinfo=utc)),
        ),
    ]
