# Generated by Django 3.0.8 on 2021-11-04 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0035_auto_20211104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 57, 34, 383947, tzinfo=utc)),
        ),
    ]
