# Generated by Django 3.0.8 on 2021-10-27 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0036_auto_20211027_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 17, 10, 30, 742469, tzinfo=utc)),
        ),
    ]
