# Generated by Django 3.0.8 on 2021-10-28 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0038_auto_20211028_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 3, 27, 34, 184912, tzinfo=utc)),
        ),
    ]
