# Generated by Django 3.0.8 on 2021-10-26 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20211025_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 3, 4, 54, 480831, tzinfo=utc)),
        ),
    ]
