# Generated by Django 3.0.8 on 2021-10-28 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_auto_20211028_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driving_license_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 3, 42, 29, 724094, tzinfo=utc)),
        ),
    ]
