# Generated by Django 3.0.8 on 2021-10-28 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_auto_20211028_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 13, 30, 15, 198991, tzinfo=utc)),
        ),
    ]
