# Generated by Django 3.0.8 on 2021-10-27 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_auto_20211027_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 10, 20, 50, 215650, tzinfo=utc)),
        ),
    ]
