# Generated by Django 3.0.8 on 2021-10-27 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0023_auto_20211027_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 10, 22, 14, 285773, tzinfo=utc)),
        ),
    ]
