# Generated by Django 3.0.8 on 2021-10-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0017_auto_20211026_0204'),
        ('driver', '0005_auto_20211026_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('total_cost', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
                ('driver_rating', models.IntegerField(default=0)),
                ('passenger_rating', models.IntegerField(default=0)),
                ('ride_status', models.IntegerField(choices=[(0, 'INITIATED'), (1, 'ACCEPTED'), (2, 'COMPLETED'), (3, 'PAID')], default=0)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.Driver')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passenger.Passenger')),
            ],
        ),
    ]
