# Generated by Django 3.0.8 on 2021-10-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20211026_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.IntegerField(choices=[(0, 'INITIATED'), (1, 'ACCEPTED'), (3, 'STARTED'), (2, 'CANCELLED'), (4, 'COMPLETED'), (5, 'PAID')], default=0),
        ),
    ]
