# Generated by Django 3.0.8 on 2021-10-28 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_auto_20211027_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
