INITIATED = 0
ACCEPTED = 1
STARTED = 2
CANCELLED = 3
COMPLETED = 4
PAID = 5

RIDE_STATUS_TYPES = [
    (INITIATED, 'INITIATED'),
    (ACCEPTED, 'ACCEPTED'),
    (STARTED, 'STARTED'),
    (CANCELLED, 'CANCELLED'),
    (COMPLETED, 'COMPLETED'),
    (PAID, 'PAID')
]
