# Generated by Django 3.0.8 on 2021-10-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ride', '0005_auto_20211027_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('payment_status', models.CharField(choices=[('payment_started', 'payment_started'), ('payment_completed', 'payment_completed')], default='payment_started', max_length=50)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride.Ride')),
            ],
        ),
    ]
